server:
  port: 8081

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/db_bogus_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: bogus
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update


#
#spring:
#  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path
#  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
#  datasource:
#    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
#    url: jdbc:h2:~/test # jdbc:h2:./data/testdb  # H2 접속 정보
#    username: bogus  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
#    password: 1234 # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
#
#  security:
#      user:
#          name: bogus
#          password: 1234